apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-handler-17784
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/service-handler-17784
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
